### ISSUE TITLE
build:viewer-zip intermittently fails

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/A2JViewer#117]
running 
`npm run build:viewer-zip` sometimes fails with below message

```
uh-oh something went wrong!
(node:15382) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/vol/data/sites/viewer.a2j.org/a2jviewer/License.md'
    at Object.lstatSync (fs.js:1007:3)
    at /vol/data/sites/viewer.a2j.org/a2jviewer/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:308:16
    at getStats (/vol/data/sites/viewer.a2j.org/a2jviewer/node_modules/fs-extra/lib/copy-sync/copy-sync.js:46:14)
    at startCopy (/vol/data/sites/viewer.a2j.org/a2jviewer/node_modules/fs-extra/lib/copy-sync/copy-sync.js:41:10)
    at Object.copySync (/vol/data/sites/viewer.a2j.org/a2jviewer/node_modules/fs-extra/lib/copy-sync/copy-sync.js:36:10)
    at makePackageFolder (/vol/data/sites/viewer.a2j.org/a2jviewer/bin/make-viewer-package:59:6)
    at /vol/data/sites/viewer.a2j.org/a2jviewer/bin/make-viewer-package:33:5
(node:15382) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15382) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

unlcear why it is intermittent. Likely due to correct file is `LICENSE.md` not `License.md`

**Comment by tobiasnteireho** [comment]
this may be intermittent because of case sensitivity between file systesms.
